version: '3.5'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bam"
    volumes:
      - pg_data:/var/lib/postgresql:delegated
    hostname: postgresql
  bam:
    build:
      context: ./
      target: bam
    image: bam
    depends_on:
      - postgresql
    ports:
      - "5000:5000"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@postgresql/bam"
    hostname: bam
  bam-dev:
    build:
      context: ./
      target: bam-dev
    image: bam-dev
    profiles: ["tests"]

volumes:
  pg_data:
