version: '3.5'
services:
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "bam"
    volumes:
      - pg_data:/var/lib/postgresql:delegated
    hostname: postgresql
volumes:
  pg_data:
